trigger:
- main

resources:
- repo: self

pool: 'Default'


steps:
- checkout: self

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  displayName: "Run unit tests"
  inputs:
    command: test
    projects: "**/*[Tt]est*/*.csproj"
    publishTestResults: true
    arguments: '--collect:"XPlat Code Coverage"'

- task: reportgenerator@5
  displayName: Generate coverage report
  inputs:
      reports: "$(Agent.TempDirectory)/**/*.cobertura.xml"
      targetdir: "$(Agent.TempDirectory)/CoverageResults"

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage results
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: "$(Agent.TempDirectory)/CoverageResults/Cobertura.xml"

- task: Docker@2
  inputs:
    repository: 'localhost:5000/backend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: './'
    tags: |
      $(Build.BuildId)
      latest

- task: CmdLine@2
  inputs:
    script: 'docker compose up -d'
    workingDirectory: '~/dockermonitor'
