version: '3.4'

services:
  dockermonitor.core:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DockerStatsContext=server=sqlserver;database=ContainerStats;user=root;password=Development_Password;
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  db:
    environment:  
      MARIADB_DATABASE: "ContainerStats"
      MARIADB_ROOT_PASSWORD: "Development_Password"
    ports:  
      - "3306:3306"
    expose:  
      - 1433
    restart: always
    volumes:
      - ./.mysql:/var/lib/mysql