version: '3.4'

services:
  dockermonitor.core:
    image: ${DOCKER_REGISTRY-}dockermonitorcore
    build:
      context: .
      dockerfile: DockerMonitor.Core/Dockerfile
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock" 
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: "sqlserver"
    hostname: "sqlserver"
  grafana:
    image: grafana/grafana
    ports:
     - "3000:3000"
    volumes:
     - "./.grafana:/var/lib/grafana" 