version: '3.4'

services:
  dockermonitor.core:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  db:
    environment:  
      SA_PASSWORD: "Development_Password"
      ACCEPT_EULA: "Y"
    ports:  
      - "1433:1433"
    expose:  
      - 1433
    restart: always
    volumes:
      - ./.mssql/data:/var/opt/mssql/data 
      - ./.mssql/log:/var/opt/mssql/log